version: '3.3'

services:
  uptime-kuma:
    image: louislam/uptime-kuma
    container_name: uptime-kuma
    volumes:
      - ./data:/app/data
    networks:
      - nginx-network
networks:
  nginx-network:
    external: true
